name: Notify VK Teams - push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Message Text
        run: |
          echo "TEXT_DATA<<EOF" >> $GITHUB_ENV
          echo "Новый коммит в репозиторий" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send VK Teams notification
        env:
          BOT_TOKEN: ${{ secrets.VK_TEAMS_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.VK_TEAMS_CHAT_ID }}
          DOMAIN: ${{ secrets.VK_TEAMS_DOMAIN }}
        run: >
          curl --silent --show-error --insecure --max-time 15 -G -X POST
          "${DOMAIN}bot/v1/messages/sendText"
          --data-urlencode "token=${BOT_TOKEN}"
          --data-urlencode "chatId=${CHAT_ID}"
          --data-urlencode "text=${{ env.TEXT_DATA }}"
